template = """
You are Mutual Fund Products / Values, expert.
Your answer needs to be generated based on context of ** question ** and ** Reviewers Feedback **.
You can refer and provided ** Mutual Fund Product **.
Generate max 30 word write up around it. It can be less aswell.
Do not hallucinate. Return response in json format.
Set "next_agent" : "reviewer", "message" : "Review my reponse", "response" = "<<Response generated by LLM based on ** Mutual Fund Product ** and ** Reviewers Feedback **>>"

Mutual Fund Product :
{Placeholder1} these are Mutual Fund Products

Reviewers Feedback (If value is EMPTY, please ignore) : 
{Placeholder2}
"""

json = {
    "type" : "object",
    "properties" : {
        "next_agent" : {
            "type" : "string",
            "description" : "reviewer"
        },
        "message" : {
            "type" : "string",
            "description" : "Review my reponse"
        },
        "response": {
            "type" : "string",
            "description" : "<<This should have message which was generated by LLM based on provided context.>>"
        },
        "files" : {
            "type" : "List",
            "description" : "Holds anchor tag with urls for files to be downloaded."
		}
    },
    "required" : ["next_agent", "message", "response", "files"]
}


#QUERY 
template2 = """
You are Microsoft SQL Query Expert.
You are responsible for writing syntactically correct Microsoft SQL Queries. Do not add comments inbetween Queries.
You would analyze the ** Question ** and ** Reference Table Schema ** to generate correct SQL query.
You need to understand and consider that user will not always provide exact textual values. Where ever required you should use LIKE operation in WHERE clause.
So based on the ** Reference Column Details ** provided below you need to make necessary adjustments to query.
You should never use * clause, You should always give specific column names after analysing ** question **
Be mindful. MS SQL does not have keyword LIMIT, you would need to use TOP.
Do not hallucinate. Return response in json format. Do not append any extra filler text like json\n.
Set "sql_query" : "<<Return SQL Query>>", "response" : "<<Print descriptive message as what this SQL query does.>>"

** Reference Table Schema **
{Placeholder1}

** Reference Column Details **
{Placeholder2}
"""

reference_table_schema = """

CREATE TABLE [dbo].[tbl_mutual_funds_product](
	[Code] [varchar](15) NOT NULL,
	[Name] [varchar](250) NULL,
	[Fund_House] [varchar](250) NULL,
	[Category] [varchar](250) NULL,
	[Type] [varchar](250) NULL,
	[NAV] [decimal](18, 5) NULL,
	[NAV_Date] [date] NULL,
	[Returns_1D] [decimal](18, 5) NULL,
	[Returns_1W] [decimal](18, 5) NULL,
	[Returns_1M] [decimal](18, 5) NULL,
	[Returns_3M] [decimal](18, 5) NULL,
	[Returns_6M] [decimal](18, 5) NULL,
	[Returns_1Y] [decimal](18, 5) NULL,
	[Returns_3Y] [decimal](18, 5) NULL,
	[Returns_5Y] [decimal](18, 5) NULL,
	[Returns_CAGR_1Y] [decimal](18, 5) NULL,
	[Returns_CAGR_3Y] [decimal](18, 5) NULL,
	[Returns_CAGR_5Y] [decimal](18, 5) NULL,
	[Risk_Volatility] [decimal](18, 5) NULL,
	[Risk_Sharpe_Ratio] [decimal](18, 5) NULL,
	[Risk_Max_Drawdown] [decimal](18, 5) NULL,
PRIMARY KEY CLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

"""

reference_column_details = """
Column names are mentioned in square brackets [] and Column values are mentioned in double quotes ""

[Code] : It contain UNIQUE 6 digit numeric code which represent respective Mutual Fund Product. It is a Primary Key.
[Name] : It represents name of the Mutual Fund Product. 
[Fund_House] : It represents name of the Fund House / Company / Parent Company / Entity under which the respective Mutual Fund is launched.
[Category] : It represent Category of the respective Mutual Fund. Valid Category values are : 
"1102 Days", "Debt Scheme - Low Duration Fund", "IDF", "G", "1100 days", "1194 DAYS", "Equity Scheme - Multi Cap Fund", "Other Scheme - Other  ETFs", "DIRECT", 
"1111 DAYS", "Equity Scheme - Focused Fund", "Payout", "Debt Scheme - Medium to Long Duration Fund", "Half Yearly Dividend", "Gilt", 
"Equity Scheme - Large & Mid Cap Fund", "Hybrid Scheme - Conservative Hybrid Fund", "Debt Scheme - Medium Duration Fund", "Daily", "erstwhile Cash Option", 
"Debt Scheme - Gilt Fund with 10 year constant duration", "1099 Days", "Equity Scheme - Dividend Yield Fund", "Formerly Super Institutional Plan", 
"Hybrid Scheme - Balanced Hybrid Fund", "Merger of Capex & Energy Opportunities", "Equity Scheme - ELSS", "5 Year Plan", "Debt Scheme - Liquid Fund", 
"Other Scheme - Index Funds", "Equity Scheme - Value Fund", "Hybrid Scheme - Equity Savings", "Hybrid Scheme - Aggressive Hybrid Fund", "Debt Scheme - Dynamic Bond", 
"1124 Days", "19 months Plan", "FV Rs 32.161", "1116 Days", "Debt Scheme - Ultra Short Duration Fund", "1141 Days", "91 Days", "1", "Other Scheme - FoF Overseas", 
"Debt Scheme - Floater Fund", "Liquid", "Solution Oriented Scheme - Children’s Fund", "466 DAYS", "Debt Scheme - Corporate Bond Fund", "ELSS", 
"Equity Scheme - Small Cap Fund", "Debt Scheme - Banking and PSU Fund", "Income", "Other Scheme - Gold ETF", "Debt Scheme - Long Duration Fund", "Annual Dividend", 
"54EB Growth", "Compulsory Reinvestment", "Debt Scheme - Gilt Fund", "Growth", "Analyst's Conviction Equalized", "Equity Scheme - Contra Fund", 
"Debt Scheme - Short Duration Fund", "1305 Days", "Money Market", "Equity Scheme - Sectoral/ Thematic", "Debt Scheme - Credit Risk Fund", 
"Debt Scheme - Money Market Fund", "Hybrid Scheme - Multi Asset Allocation", "Hybrid Scheme - Dynamic Asset Allocation or Balanced Advantage", 
"Equity Scheme - Mid Cap Fund", "Equity Scheme - Large Cap Fund", "Equity Scheme - Focussed Fund", "Debt Scheme - Overnight Fund", "Formerly Known as IIFL Mutual Fund", 
"Solution Oriented Scheme - Retirement Fund", "Hybrid Scheme - Arbitrage Fund", "1150 DAYS", "Balanced", "Other Scheme - FoF Domestic", "1098 Days"
[Type] : It represents Type of respective Mutual Fund Product. Valid Type values are :
"HDFC EOF - II - 1100D June 2017", "Franklin India Fixed Tenure Fund - Series XII - Plan C", "DHFL Pramerica Hybrid Fixed Term Fund - Series 10 - Annual Dividend", 
"BARODA PIONEER CONSERVATIVE HYBRID FUND - Plan B", "Aditya Birla Sun Life Liquid Fund-Retail", "Close Ended Schemes", "SBI Magnum Income Plus Fund - Savings Plan", 
"BARODA PIONEER INCOME FUND - Plan B", "Baroda Pioneer Treasury Advantage Fund - Plan B", "Baroda Pioneer ELSS 96 Plan B", "Aditya Birla Sun Life Income Fund-Plan G", 
"Sundaram Infrastructure Advantage Fund", "Aditya Birla Sun Life Fixed Term Plan - Series QY", "Baroda Pioneer Banking and Financial Services Fund - Plan B", 
"SBI Debt Fund Series A - 29", "DHFL Pramerica Mid Cap Fund - Series 1 - Direct Plan - Dividend", "SBI DEBT FUNDS SERIES A - 39", 
"Sundaram Money Fund Regular weekly Dividend. Rein", "Baroda Pioneer Dynamic Bond Fund - Plan B", "IDFC EQUITY OPPORTUNITY SERIES 6", 
"DHFL Pramerica Mid Cap Fund - Series 1 - Regular Plan - Dividend", "UTI FTIF Series XVII -IX", "BNP PARIBAS LOW DURATION Fund-Regular Plan- Daily Dividend Option", 
"SBI DEBT FUND SERIES A - 44", "Interval Fund Schemes", "HDFC Overnight Fund - Dividend option", "BARODA PIONEER GILT FUND - Plan B", "Kotak FMP Series 171", 
"BARODA PIONEER LIQUID FUND - PLAN B", "DHFL Pramerica Hybrid Fixed Term Fund - Series 17 - Regular Plan - Dividend", "JM MIP Fund", 
"CANARA ROBECO FIXED MATURITY PLAN- Series 4", "JM G-Sec Fund -", "UTI FTIF Series XXII-XIV", "Kotak Bond Short Term Plan-", "Axis Hybrid Fund - Series 7", 
"JM Floater Short Term Fund -", "JM Low Duration Fund", "DHFL Pramerica Large Cap Fund - Series 3 - Direct Plan - Dividend", 
"DHFL Pramerica Large Cap Fund - Series 1 - Regular Plan - Dividend", "SBI DEBT FUND SERIES C - 9", "DHFL Pramerica Hybrid Fixed Term Fund - Series 4 - Dividend", 
"DHFL Pramerica Hybrid Fixed Term Fund - Series 13 - Regular Plan - Dividend", "BARODA PIONEER HYBRID EQUITY FUND - Plan B", "Kotak FMP Series 180", 
"Open Ended Schemes", "Baroda Pioneer Credit Risk Fund -Plan B-", "UTI Focussed Equity Fund - Series II", "Kotak FMP Series 175", 
"DHFL Pramerica Hybrid Fixed Term Fund - Series 11 - Direct Plan - Dividend", "DHFL Pramerica Large Cap Fund - Series 3 - Regular Plan - Dividend", 
"Sundaram Low Duration Fund Regular Weekly Dividend", "Aditya Birla Sun Life Gilt Plus-Regular Plan", 
"DHFL Pramerica Hybrid Fixed Term Fund - Series 14 - Regular Plan - Dividend", "Baroda Pioneer Short Term Bond Fund - Plan B -", 
"Invesco India Fixed Maturity Plan-Series 24-Plan F", "DSP  A.C.E. Fund", "Axis Fixed Term Plan - Series 97", "HDFC Index FundSensex Plan", 
"IIFCL Mutual Fund", "JM Ultra Short Duration Fund -", "DHFL Pramerica Large Cap Fund - Series 1 - Direct Plan - Dividend", "JM Multicap Fund", 
"DHFL Pramerica Hybrid Fixed Term Fund - Series 12 - Regular Plan - Dividend", "DHFL Pramerica Hybrid Fixed Term Fund - Series 5 - Dividend", 
"ICICI Prudential Money Market Fund Retail Growth", "Baroda Pioneer Hybrid Fund- Series 1- Plan B", "Axis Fixed Term Plan - Series 96", 
"IL&FS Mutual Fund", "JM Arbitrage Fund", "HDFC HOF - I - 1140D November 2017", "360 ONE Mutual Fund", "Invesco India Fixed Maturity Plan - Series 25 - Plan D", 
"DHFL Pramerica Hybrid Fixed Term Fund - Series 6 - Dividend", "JM Short Term Fund", "JM Liquid Fund Unclaimed Redemption IEF", 
"DHFL Pramerica Hybrid Fixed Term Fund - Series 19 - Regular Plan - Dividend"
[NAV] : It represents Net Asset Value of that respective Mutual Fund Product.
[NAV_Date] : It represents thats Date when the Net Asset Value (NAV) was calculated. 
[Returns_1D] : It represents Percentage of Returns generated by that respective Mutual Fund Product in 1 Day. 
[Returns_1W] : It represents Percentage of Returns generated by that respective Mutual Fund Product in 1 Week.
[Returns_1M] : It represents Percentage of Returns generated by that respective Mutual Fund Product in 1 Month.
[Returns_3M] : It represents Percentage of Returns generated by that respective Mutual Fund Product in 3 Months.
[Returns_6M] : It represents Percentage of Returns generated by that respective Mutual Fund Product in 6 Months.
[Returns_1Y] : It represents Percentage of Returns generated by that respective Mutual Fund Product in 1 Year.
[Returns_3Y] : It represents Percentage of Returns generated by that respective Mutual Fund Product in 3 Years.
[Returns_5Y] : It represents Percentage of Returns generated by that respective Mutual Fund Product in 5 Years.
[Returns_CAGR_1Y] : It represents Compound annual growth rate (in Percentage) generated by that respective Mutual Fund Product in 1 Year.
[Returns_CAGR_3Y] : It represents Compound annual growth rate (in Percentage) generated by that respective Mutual Fund Product in 3 Years.
[Returns_CAGR_5Y] : It represents Compound annual growth rate (in Percentage) generated by that respective Mutual Fund Product in 5 Years.
[Risk_Volatility] : It represents the degree to which that respective Mutual Fund Product value changes over time, and indicates the level of risk. 
[Risk_Sharpe_Ratio] : The Sharpe ratio is a financial metric that measures the risk-adjusted performance of a mutual fund. 
A higher Sharpe ratio indicates better risk-adjusted performance. A Sharpe ratio above 1.0 is considered acceptable to good, above 2.0 is considered very good, and above 3.0 is considered excellent.
The Sharpe ratio is most useful when comparing similar investments, like mutual funds that track the same index. However, investments with a higher Sharpe ratio can be more volatile than those with a lower ratio.
[Risk_Max_Drawdown] : Maximum drawdown (MDD) is a metric that measures the maximum percentage loss in the value of a portfolio or investment between a peak and a trough. 
It's a key indicator of risk and is used by investment firms like mutual funds to quantify downside risk.
"""

template3 = """
You are expert Data Analyst.
You are responsible to analyze the ** User Question **, ** Data **, ** Reviewers Feedback ** and generate a well structured, crisp, professional and descriptive response.
In your descriptive response, You dont have to mention anywhere that you have analyzed ** Data **, it should sound like a Final Authorative Report.
You have to be very specific about the period and answer with the same context.
Do not limit your knowledge until October 2023. Refer to information from ** Data ** and ** Reviewers Feedback **
** Data ** will provide you with multiple data points, but you need to formulate response based on only important fields which are related to the ** Question **
Refer to ** Reviewers Feedback ** also and formulate response accordingly.
Do not hallucinate. 
Return well structured, crisp, professional and descriptive ** response **. 
Return only in below json format. Do not append any extra filler text like json\n.
Set "next_agent" : "reviewer", "message" : "Review my reponse", "response" : "<<Response needs to be descriptive in human langugage based on analysis of ** Question **, ** Data ** and ** Reviewers Feedback **. It should not be dictionary.>>"
           
** Data **
{Placeholder1}

** Reviewers Feedback ** (If value is EMPTY, please ignore) : 
{Placeholder2}
"""


# If the ** Data ** is EMPTY, then 
# Set "next_agent" : "reviewer", "message" : "Review my reponse", "response" : "Apologies, I dont have details to answer your question"
