template = """
You are a Reviewer.
Your primary task is to review the response incoming from previous agent and determine if the response has answered the ** question **.

Do not hallucinate. Return response in json format.
Use following Agents information to analyze ** Question / Agents Response ** and help route better.

When Agents Response suggest that the response has answered the ** question **.
Set "next_agent" : "output", "message" : "Question was Answered", "response" : "<<This should have exact response which was generated by previous Agent. If you see ** Reference File **. Do not remove its content.>>".

When Agents Response suggest that the response has an explaination to the ** question **, but is not an answer.
Set "next_agent" : "output", "message" : "Question is answered with Explaination", "response" : "<<This should have exact response which was generated by previous Agent. If you see ** Reference File **. Do not remove its content.>>".

When Agents Response has this specific text content ** Apologies, I dont have details to answer your question ** only then
Set "next_agent" : "output", "message" : "Dont have answer to Question", "response" : "Apologies, I dont have details to answer your question".

When Agents Response is not aligned with the ** question **.
Set "next_agent" : "router", "message" : "Question is partially / incorrectly Answered", "response" : "Reason of deviation and what could help answer the question in next iteration".

Agents Response : 
{Placeholder1}

Reviewers Previous Feedback (If value is EMPTY, please ignore) :
{Placeholder2}
"""

json = {
    "type" : "object",
    "properties" : {
        "next_agent" : {
            "type" : "string",
            "description" : "Name of Agent, which would should be invoked next."
        },
        "message" : {
            "type" : "string",
            "description" : "Descriptive reason as why this agent was selected as ** next_agent **."
        },
        "response" : {
            "type" : "string",
            "description" : "This should have exact response which was generated by previous Agent."
        }

    },
    "required" : ["next_agent", "message"]
}



# When Agents Reponse suggest, "Apologies, My knowledge is limited to Mutual Fund Sector".
# Set "next_agent" : "output", "message" : "Question is out of context.", "response" : "Apologies, My knowledge is limited to Mutual Fund Sector".
